"""create initial tables

Revision ID: 8fd497f72dfb
Revises: 
Create Date: 2026-05-08 09:53:07.896536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fd497f72dfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases_celulas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador numérico único de la clase de célula.'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment="Nombre canónico de la clase celular, ej: 'Neutrofilo', 'Linfocito', 'Monocito', 'Eosinofilo', 'Basofilo'."),
    sa.Column('fechaBaja', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de baja lógica. Si es NULL, la clase está activa. Si tiene valor, fue deshabilitada sin eliminarse del catálogo.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del usuario (UUID v4).'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Dirección de correo electrónico, debe ser única en el sistema.'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Hash de la contraseña del usuario (ej. bcrypt).'),
    sa.Column('fechaCreacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de creación del registro en la base de datos.'),
    sa.Column('fechaModificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de la última modificación del registro.'),
    sa.Column('fechaBaja', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de baja lógica. Si es NULL, el usuario está activo. Si tiene valor, el usuario fue dado de baja sin eliminarse de la BD.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analisis',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del análisis (UUID v4).'),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='FK al usuario propietario del análisis.'),
    sa.Column('imagen_url', sa.String(length=500), nullable=False, comment='URL o ruta del archivo de imagen a analizar (almacenado en object storage).'),
    sa.Column('estado', sa.String(length=50), server_default='PENDING', nullable=False, comment='Estado del ciclo de vida del análisis. Valores esperados: PENDING, PROCESSING, COMPLETED, FAILED.'),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de creación del análisis.'),
    sa.Column('fechaBaja', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de baja lógica. Si es NULL, el análisis está activo. Si tiene valor, fue marcado como eliminado sin borrarse de la BD.'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_usuario_id'), 'analisis', ['usuario_id'], unique=False)
    op.create_table('detecciones',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único de la detección (UUID v4).'),
    sa.Column('analisis_id', sa.UUID(), nullable=False, comment='FK al análisis al que pertenece esta detección.'),
    sa.Column('clase_id', sa.Integer(), nullable=False, comment='FK al catálogo de clases celulares (tipo de glóbulo detectado).'),
    sa.Column('confianza', sa.Float(), nullable=True, comment='Puntuación de confianza del modelo de IA (valor entre 0.0 y 1.0).'),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Bounding box de la célula detectada en formato JSONB. Estructura esperada: [x_min, y_min, x_max, y_max].'),
    sa.Column('fechaBaja', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de baja lógica. Si es NULL, la detección está activa. Si tiene valor, fue descartada sin eliminarse de la BD.'),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clase_id'], ['clases_celulas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detecciones_analisis_id'), 'detecciones', ['analisis_id'], unique=False)
    op.create_index(op.f('ix_detecciones_clase_id'), 'detecciones', ['clase_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del registro de feedback (UUID v4).'),
    sa.Column('analisis_id', sa.UUID(), nullable=False, comment='FK al análisis sobre el cual se está emitiendo el feedback.'),
    sa.Column('deteccion_id', sa.UUID(), nullable=True, comment='FK a la detección original que se está corrigiendo. Es NULL cuando el bioquímico agrega una célula nueva no detectada por la IA.'),
    sa.Column('tipoCorreccion', sa.String(length=50), nullable=False, comment='Tipo de corrección aplicada. Valores esperados: FALSO_POSITIVO, NUEVA_DETECCION, CAMBIO_CLASE.'),
    sa.Column('claseCorregida', sa.Integer(), nullable=True, comment='FK a la clase celular correcta según el bioquímico. Usado principalmente en correcciones de tipo CAMBIO_CLASE y NUEVA_DETECCION.'),
    sa.Column('bbox_corregido', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bounding box corregido o nuevo en formato JSONB. Estructura esperada: [x_min, y_min, x_max, y_max]. Requerido para NUEVA_DETECCION, opcional para CAMBIO_CLASE.'),
    sa.Column('fechaBaja', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de baja lógica. Si es NULL, el feedback está vigente. Si tiene valor, fue anulado sin eliminarse de la BD.'),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claseCorregida'], ['clases_celulas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deteccion_id'], ['detecciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_analisis_id'), 'feedback', ['analisis_id'], unique=False)
    op.create_index(op.f('ix_feedback_deteccion_id'), 'feedback', ['deteccion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_deteccion_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_analisis_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_detecciones_clase_id'), table_name='detecciones')
    op.drop_index(op.f('ix_detecciones_analisis_id'), table_name='detecciones')
    op.drop_table('detecciones')
    op.drop_index(op.f('ix_analisis_usuario_id'), table_name='analisis')
    op.drop_table('analisis')
    op.drop_table('usuarios')
    op.drop_table('clases_celulas')
    # ### end Alembic commands ###
